### PR TITLE
Make the crate `no_std` + `alloc` (rebased)

### LINKED ISSUE #26: no_std + alloc
This crate _should_ be possible to write using only [`core`](https://doc.rust-lang.org/core/) and [`alloc`](https://doc.rust-lang.org/alloc/), and thus be usable in `no_std` environments.

The `hashbrown` implementation should be hugely helpful in figuring out how to do this. In particular, see the magical incantations in [`src/lib.rs`](https://github.com/rust-lang/hashbrown/blob/master/src/lib.rs) and the use of `alloc` and `core` in [`src/raw/mod.rs`](https://github.com/rust-lang/hashbrown/blob/master/src/raw/mod.rs). We may be able to simplify some of those since `hashbrown` has to [pull some tricks](https://github.com/rust-lang/hashbrown/blob/6f5826ed934a5e6342681c27618bea71f9b0c800/Cargo.toml#L23-L26) so that it can be pulled into `std`. Compare for example with the `no_std` support in [`crossbeam-epoch/src/lib.rs`](https://github.com/crossbeam-rs/crossbeam/blob/c0a999d2f15935a895cbcee16f3b46746d5174b7/crossbeam-epoch/src/lib.rs#L59).

There are a couple of things that we have to figure out how to operate in a `no_std` environment:
 - `crossbeam-epoch` will need `default-features = false` and `features = ["alloc"]`. This will [remove `epoch::pin`](https://github.com/crossbeam-rs/crossbeam/blob/c0a999d2f15935a895cbcee16f3b46746d5174b7/crossbeam-epoch/src/lib.rs#L104) (but not `epoch::Guard` I think), and we'll need to figure out whether the API is still usable (and maybe include some examples).
 - `RandomState` is only available with `std`, so we will want to add a `std` feature (which is on by default) and only expose it when the feature is enabled. We'll also have to figure out how that affects the [`default value for S`](https://github.com/jonhoo/flurry/blob/2a5bd258fa805e89715f7dbd52b63bddf736490f/src/lib.rs#L262).
 - Neither `num_cpus` nor `Once` (which we use for [`NCPU`](https://github.com/jonhoo/flurry/blob/2a5bd258fa805e89715f7dbd52b63bddf736490f/src/lib.rs#L247)) are available on `no_std`. We'll need to figure out how to [determine the stride](https://github.com/jonhoo/flurry/blob/2a5bd258fa805e89715f7dbd52b63bddf736490f/src/lib.rs#L837) for transfers without it.
 - We currently use `std::thread::yield_now` if we detect an [initialization race](https://github.com/jonhoo/flurry/blob/2a5bd258fa805e89715f7dbd52b63bddf736490f/src/lib.rs#L472-L473). It's not entirely clear what we do in this case in a `no_std` environment. I _think_ it is fine for us to use [`spin_loop_hint`](https://doc.rust-lang.org/core/sync/atomic/fn.spin_loop_hint.html) if the `std` isn't set for the following reason: for there to be a race, there _must_ be another thread running concurrently with us. That thread cannot be blocked on us, since we are not in any mutually-exclusive section. So our goal is just to not waste cycles and give it some time to complete. It is not a _requirement_ that we fully yield.

### PR DESCRIPTION
**Pull request by jonhoo**
This is effectively a squash + rebase of #44 on top of #47.

It squashes the commits so that it is easier to see what's going on. @cuviper's comments from https://github.com/jonhoo/flurry/pull/44#pullrequestreview-351018649 still apply, as does the question about whether we are even willing to make this change (https://github.com/jonhoo/flurry/pull/44#issuecomment-580378812). There's a little twitter straw poll [here](https://twitter.com/jonhoo/status/1222942509606653952). To summarize:

> The new `L` parameter is unfortunate, but I don't see how we get around it if we want to support `no_std`. I think the only question is "is it important is it for us to support `no_std` for this crate". If the answer is that it seems valuable, then I think this is how it has to be.

Thanks to @GarkGarcia for all the hard work on #44 -- that's the majority of this change.

Closes #44. Fixes #26.

### CODE REVIEW

**Comment by jonhoo** [comment]
Pushed some changes now that I think makes this patch a bit more pleasant. There is still the `L` parameter, but it should be much less noticeable since most users should be interacting with the `HashMap` type alias, which does not have it.

**Comment by jonhoo** [comment]
Not sure if this alleviates some of your concerns from #44 @cuviper?

**Comment by GarkGarcia** [comment]
> The new `L` parameter is unfortunate, but I don't see how we get around it if we want to support `no_std`. I think the only question is "is it important is it for us to support `no_std` for this crate". If the answer is that it seems valuable, then I think this is how it has to be.

Can't we also provide a default to the `L` parameter? That would alleviate some of the pain. No idea what that default would be in `no_std` though.

**Comment by jonhoo** [comment]
Yeah, that's the problem -- on `no_std`, that parameter has no reasonable default. That in turn means that it cannot be the last type parameter (since you cannot have a type parameter without a default _after_ one with a default). Which again in turn means that anywhere people specify map types, if they want to use a custom hasher, they have to write `HashMap<K, V, _, S>`. Also, the extra generic type is real awkward for anyone who wants to be generic over a map, though that's something we won't completely get away from anyway.

**Comment by cuviper** [comment]
I guess the type alias helps hide the complexity, at the loss of available iterator types. I'm not sure if that's a net win -- I guess that's still driven by how desirable `no_std` is in the first place.

Did you manage to gather compelling use-cases? And can you prototype that this crate actually works in those cases? What `L` would you use?

**Comment by jonhoo** [comment]
I agree, it's definitely still a cost.

As far as use-cases goes, the response was pretty meager. https://twitter.com/thequux/status/1223248563523723264 and https://twitter.com/thequux/status/1223248563523723264 were the primary ones.

My current take is that we should probably just close this, with a note that we'd be open to considering if someone has a compelling use-case they're willing to also commit some time to supporting.

**Comment by cuviper** [comment]
> My current take is that we should probably just close this, with a note that we'd be open to considering if someone has a compelling use-case they're willing to also commit some time to supporting.

I think that makes sense.

**Comment by jonhoo** [comment]
All right, I'll close this and the corresponding issue then :)

**Pull request closed without merging**
