### PR TITLE
FlurryHashMap Clone

### PR DESCRIPTION
**Pull request by danielSanchezQ**
Implemented Clone for FlurryHashMap
Implemented Clone for Table
Added simple clone map test by checking values on preloaded map and cloned one

### CODE REVIEW

**Comment by danielSanchezQ** [comment]
I'm working on updating the branch with the latest changes

@jonhoo , It was simple I think but I have the feeling I'm missing something here. Should the Clone implementation be concurrent safer somehow? Thanks

**Comment by jonhoo** [comment]
Hmm, I think that's probably not a safe way to do it, because you will be aliasing all of the keys, values, and nodes. They place to start is probably to do the same thing as the [Java `Map` constructor](https://github.com/jonhoo/flurry/blob/f6cdb55aca1d15e863f3790cad9dfb3095ec69f7/jsr166/src/ConcurrentHashMap.java#L821), which really just allocates a new map (with the necessary capacity) and then inserts all the elements from the old map one at a time. In Rust you will have to clone each key/value pair you iterate over before inserting into the new map, but that should be fine!

**Comment by danielSanchezQ** [comment]
That makes completely sense. This should have been a draft instead, sorry for that. I'll just close this one a open a proper one next time.

**Comment by jonhoo** [comment]
Don't worry about it -- feel free to just re-open this one and continue using it :)

**Pull request closed without merging**
