### PR TITLE
Add basic .travis.yml and README badges

### PR DESCRIPTION
**Pull request by rkm**
Hi, thanks again for the streams.

I felt like contributing something, so here's a small starter TravisCI config.

### CODE REVIEW

**Comment by ritobanrc** [comment]
How does TravisCI compare with Github Actions?

**Comment by rkm** [comment]
Not really sure how to answer that to be honest. I spotted .travis.yml files in some of @jonhoo's other projects though, so decided to go with this.

**Comment by jonhoo** [comment]
Thank you! I prefer to use the default template from [crate-ci/azure-pipelines](https://github.com/crate-ci/azure-pipelines) though, since it runs a bunch more things like run rustfmt, clippy, and code coverage. Just pushed that now so that PRs can take advantage of it. Thanks anyway though :D

**Comment by rkm** [comment]
No worries, I didn't realise that existed!

**Pull request closed without merging**
