### PR TITLE
Add test which attempts to encounter a concurrent resize and retrieval

### PR DESCRIPTION
**Pull request by jhinch**
I noticed that one of the areas of the code which had low test coverage was the [BinEntry::Moved branch in node.rs](https://github.com/jonhoo/flurry/blob/master/src/node.rs#L107). This test is designed to exercise that codepath. At least on my machine it seems to exercise the codepath but it is non-deterministic whether it will actually encounter the path.

### CODE REVIEW

**Comment by jhinch** [comment]
Of course it decides to not hit the codepath in CI. How would you feel about me adding a unit test for the `find` method so it can be tested deterministically

**Comment by jonhoo** [comment]
A unit test for that would be fantastic!

**Comment by jonhoo** [comment]
I also wonder whether you might be able to trigger more resizes by forcing all the keys into a single bucket like we do here:
https://github.com/jonhoo/flurry/blob/5fe084b408eebd984fec28ac5a8888ea0ffeab5f/tests/basic.rs#L88-L104

**Comment by jhinch** [comment]
At least when testing locally, using the one bucket hasher makes the `BinEntry::Moved` be encountered less often. I believe this is because the transfer function will transfer entire runs of entries when it can, so you actually want quite shallow bins to trigger the desired behaviour

**Comment by jonhoo** [comment]
This looks great! I do still wish we had a reliable way to check that the `next_table` pointer _in_ `Moved` was set correctly, which basically requires a resize to take place while we run a `find`. Maybe one way to do that is to set up a very large table in the test, then call `reserve` with a value large enough to trigger a resize in a separate thread, and then immediately do `get`s on the main thread?

**Comment by jhinch** [comment]
I would guess the only way to do it reliably is using a tool like loom to test each of the permutations

**Comment by jonhoo** [comment]
I _think_ the strategy I outlined above should actually work pretty reliably, but yes, ultimately we'll want something like loom as well (#34).

**Comment by jonhoo** [comment]
@jhinch would you be interested in also trying to implement the test strategy above?

**Comment by jhinch** [comment]
Apologies. I thought your comments were more speculative of how things _could_ be done rather than of something which should be changed as part of this PR. I have switched it over to use `.reserve()` instead and increased it to resize to 32K to increase likelihood of a resize being triggered

**Comment by jonhoo** [comment]
No worries. It was a bit of a speculative comments :p

I think you'll _first_ want to do many many inserts, and _then_ start the thread that does resizing. Otherwise the resizes will all finish very quickly, and you may not even see it.

**Comment by jhinch** [comment]
It looks like I've introduced a memory leak in the unit tests I added. I'm working through the problem now.

**Comment by jonhoo** [comment]
Ah, yes, the tests you've written never actually free any of the memory they allocate since you do not create a `Table` at any point (which is the thing that actually calls `defer_destroy` on stuff in its bins).

**Comment by jhinch** [comment]
Alright, all tests are passing again and merge conflicts have been resolved

**Comment by jonhoo** [comment]
Great, thanks!

**Pull request merged**
